-- MySQL Script generated by MySQL Workbench
-- Mon Feb 27 20:44:10 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Shoot4Stats
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Shoot4Stats` ;

-- -----------------------------------------------------
-- Schema Shoot4Stats
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Shoot4Stats` DEFAULT CHARACTER SET utf8 ;
USE `Shoot4Stats` ;

-- -----------------------------------------------------
-- Table `Shoot4Stats`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Shoot4Stats`.`User` ;

CREATE TABLE IF NOT EXISTS `Shoot4Stats`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `Lastname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `isAdmin` TINYINT(1) NOT NULL,
  `hashPass` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Shoot4Stats`.`Group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Shoot4Stats`.`Group` ;

CREATE TABLE IF NOT EXISTS `Shoot4Stats`.`Group` (
  `idGroup` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGroup`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Shoot4Stats`.`has_Group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Shoot4Stats`.`has_Group` ;

CREATE TABLE IF NOT EXISTS `Shoot4Stats`.`has_Group` (
  `fkUser` INT NOT NULL,
  `fkGroup` INT NOT NULL,
  PRIMARY KEY (`fkUser`, `fkGroup`),
  INDEX `fk_has_Group_Group1_idx` (`fkGroup` ASC),
  CONSTRAINT `fk_has_Group_User1`
    FOREIGN KEY (`fkUser`)
    REFERENCES `Shoot4Stats`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_has_Group_Group1`
    FOREIGN KEY (`fkGroup`)
    REFERENCES `Shoot4Stats`.`Group` (`idGroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Shoot4Stats`.`has_Coach`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Shoot4Stats`.`has_Coach` ;

CREATE TABLE IF NOT EXISTS `Shoot4Stats`.`has_Coach` (
  `fkGroup` INT NOT NULL,
  `fkUser` INT NOT NULL,
  PRIMARY KEY (`fkGroup`, `fkUser`),
  INDEX `fk_has_Coach_User1_idx` (`fkUser` ASC),
  CONSTRAINT `fk_has_Coach_Group`
    FOREIGN KEY (`fkGroup`)
    REFERENCES `Shoot4Stats`.`Group` (`idGroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_has_Coach_User1`
    FOREIGN KEY (`fkUser`)
    REFERENCES `Shoot4Stats`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Shoot4Stats`.`Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Shoot4Stats`.`Type` ;

CREATE TABLE IF NOT EXISTS `Shoot4Stats`.`Type` (
  `idType` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Shoot4Stats`.`Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Shoot4Stats`.`Location` ;

CREATE TABLE IF NOT EXISTS `Shoot4Stats`.`Location` (
  `idLocation` INT NOT NULL AUTO_INCREMENT,
  `lat` VARCHAR(45) NOT NULL,
  `long` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLocation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Shoot4Stats`.`Shoot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Shoot4Stats`.`Shoot` ;

CREATE TABLE IF NOT EXISTS `Shoot4Stats`.`Shoot` (
  `idShoot` INT NOT NULL AUTO_INCREMENT,
  `dateShoot` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `description` VARCHAR(750) NULL,
  `Title` VARCHAR(45) NOT NULL,
  `nbEnds` INT NOT NULL,
  `nbArrowsByEnd` INT NOT NULL,
  `fkType` INT NOT NULL,
  `fkUser` INT NOT NULL,
  `fkLocation` INT NULL,
  `finished` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idShoot`),
  INDEX `fk_Shoot_Type1_idx` (`fkType` ASC),
  INDEX `fk_Shoot_User1_idx` (`fkUser` ASC),
  INDEX `fk_Shoot_Location1_idx` (`fkLocation` ASC),
  CONSTRAINT `fk_Shoot_Type1`
    FOREIGN KEY (`fkType`)
    REFERENCES `Shoot4Stats`.`Type` (`idType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Shoot_User1`
    FOREIGN KEY (`fkUser`)
    REFERENCES `Shoot4Stats`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Shoot_Location1`
    FOREIGN KEY (`fkLocation`)
    REFERENCES `Shoot4Stats`.`Location` (`idLocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Shoot4Stats`.`End`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Shoot4Stats`.`End` ;

CREATE TABLE IF NOT EXISTS `Shoot4Stats`.`End` (
  `idEnd` INT NOT NULL AUTO_INCREMENT,
  `fkShoot` INT NOT NULL,
  PRIMARY KEY (`idEnd`),
  INDEX `fk_End_Shoot1_idx` (`fkShoot` ASC),
  CONSTRAINT `fk_End_Shoot1`
    FOREIGN KEY (`fkShoot`)
    REFERENCES `Shoot4Stats`.`Shoot` (`idShoot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Shoot4Stats`.`Arrow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Shoot4Stats`.`Arrow` ;

CREATE TABLE IF NOT EXISTS `Shoot4Stats`.`Arrow` (
  `idArrow` INT NOT NULL AUTO_INCREMENT,
  `posX` FLOAT NULL,
  `posY` FLOAT NULL,
  `point` INT NOT NULL,
  `fkEnd` INT NOT NULL,
  PRIMARY KEY (`idArrow`),
  INDEX `fk_Arrow_End1_idx` (`fkEnd` ASC),
  CONSTRAINT `fk_Arrow_End1`
    FOREIGN KEY (`fkEnd`)
    REFERENCES `Shoot4Stats`.`End` (`idEnd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
