-- MySQL Script generated by MySQL Workbench
-- 01/16/17 10:55:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ShootForStats
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ShootForStats` ;

-- -----------------------------------------------------
-- Schema ShootForStats
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ShootForStats` DEFAULT CHARACTER SET utf8 ;
USE `ShootForStats` ;

-- -----------------------------------------------------
-- Table `ShootForStats`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ShootForStats`.`User` ;

CREATE TABLE IF NOT EXISTS `ShootForStats`.`User` (
  `id_User` INT NOT NULL AUTO_INCREMENT,
  `Firstname` VARCHAR(45) NULL,
  `Lastname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `isAdmin` TINYINT(1) NOT NULL,
  `hashPass` VARCHAR(75) NULL,
  PRIMARY KEY (`id_User`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShootForStats`.`Group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ShootForStats`.`Group` ;

CREATE TABLE IF NOT EXISTS `ShootForStats`.`Group` (
  `id_Group` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Group`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShootForStats`.`has_Group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ShootForStats`.`has_Group` ;

CREATE TABLE IF NOT EXISTS `ShootForStats`.`has_Group` (
  `FK_User` INT NOT NULL,
  `FK_Group` INT NOT NULL,
  PRIMARY KEY (`FK_User`, `FK_Group`),
  INDEX `fk_has_Group_Group1_idx` (`FK_Group` ASC),
  CONSTRAINT `fk_has_Group_User1`
    FOREIGN KEY (`FK_User`)
    REFERENCES `ShootForStats`.`User` (`id_User`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_has_Group_Group1`
    FOREIGN KEY (`FK_Group`)
    REFERENCES `ShootForStats`.`Group` (`id_Group`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShootForStats`.`has_Coach`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ShootForStats`.`has_Coach` ;

CREATE TABLE IF NOT EXISTS `ShootForStats`.`has_Coach` (
  `FK_Group` INT NOT NULL,
  `FK_User` INT NOT NULL,
  PRIMARY KEY (`FK_Group`, `FK_User`),
  INDEX `fk_has_Coach_User1_idx` (`FK_User` ASC),
  CONSTRAINT `fk_has_Coach_Group`
    FOREIGN KEY (`FK_Group`)
    REFERENCES `ShootForStats`.`Group` (`id_Group`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_has_Coach_User1`
    FOREIGN KEY (`FK_User`)
    REFERENCES `ShootForStats`.`User` (`id_User`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShootForStats`.`Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ShootForStats`.`Type` ;

CREATE TABLE IF NOT EXISTS `ShootForStats`.`Type` (
  `id_Type` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShootForStats`.`Shoot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ShootForStats`.`Shoot` ;

CREATE TABLE IF NOT EXISTS `ShootForStats`.`Shoot` (
  `id_Shoot` INT NOT NULL AUTO_INCREMENT,
  `Date_Shoot` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Description` VARCHAR(750) NULL,
  `Title` VARCHAR(45) NOT NULL,
  `nb_End` INT NOT NULL,
  `nb_ArrowsByEnd` INT NOT NULL,
  `FK_Type` INT NOT NULL,
  PRIMARY KEY (`id_Shoot`),
  INDEX `fk_Shoot_Type1_idx` (`FK_Type` ASC),
  CONSTRAINT `fk_Shoot_Type1`
    FOREIGN KEY (`FK_Type`)
    REFERENCES `ShootForStats`.`Type` (`id_Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShootForStats`.`has_Shoot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ShootForStats`.`has_Shoot` ;

CREATE TABLE IF NOT EXISTS `ShootForStats`.`has_Shoot` (
  `FK_User` INT NOT NULL,
  `FK_Shoot` INT NOT NULL,
  PRIMARY KEY (`FK_User`, `FK_Shoot`),
  INDEX `fk_has_Shoot_Shoot1_idx` (`FK_Shoot` ASC),
  CONSTRAINT `fk_has_Shoot_User1`
    FOREIGN KEY (`FK_User`)
    REFERENCES `ShootForStats`.`User` (`id_User`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_has_Shoot_Shoot1`
    FOREIGN KEY (`FK_Shoot`)
    REFERENCES `ShootForStats`.`Shoot` (`id_Shoot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShootForStats`.`End`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ShootForStats`.`End` ;

CREATE TABLE IF NOT EXISTS `ShootForStats`.`End` (
  `id_End` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(45) NULL,
  `FK_Shoot` INT NOT NULL,
  PRIMARY KEY (`id_End`),
  INDEX `fk_End_Shoot1_idx` (`FK_Shoot` ASC),
  CONSTRAINT `fk_End_Shoot1`
    FOREIGN KEY (`FK_Shoot`)
    REFERENCES `ShootForStats`.`Shoot` (`id_Shoot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShootForStats`.`Arrow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ShootForStats`.`Arrow` ;

CREATE TABLE IF NOT EXISTS `ShootForStats`.`Arrow` (
  `id_Arrow` INT NOT NULL AUTO_INCREMENT,
  `PosX` FLOAT NULL,
  `PosY` FLOAT NULL,
  `Point` INT NOT NULL,
  PRIMARY KEY (`id_Arrow`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShootForStats`.`has_Arrow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ShootForStats`.`has_Arrow` ;

CREATE TABLE IF NOT EXISTS `ShootForStats`.`has_Arrow` (
  `FK_Arrow` INT NOT NULL,
  `FK_End` INT NOT NULL,
  PRIMARY KEY (`FK_Arrow`, `FK_End`),
  INDEX `fk_has_Arrow_End1_idx` (`FK_End` ASC),
  CONSTRAINT `fk_has_Arrow_Arrow1`
    FOREIGN KEY (`FK_Arrow`)
    REFERENCES `ShootForStats`.`Arrow` (`id_Arrow`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_has_Arrow_End1`
    FOREIGN KEY (`FK_End`)
    REFERENCES `ShootForStats`.`End` (`id_End`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
